// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)
